services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: weather_clothing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  api:
    build:
      context: .
      dockerfile: weatherCloChase.Api/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=weather_clothing;Username=postgres;Password=postgres
      - Minio__Endpoint=minio:9000
    depends_on:
      - postgres
      - minio

volumes:
  postgres_data:
  minio_data:
